name: Deploy to HuggingFace

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install UV
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync

    # - name: Run OPT analysis
    #   run: uv run python playground/run_opt_locally.py

    # - name: Run finetuning test
    #   run: uv run python playground/finetune_opt.py --optimizer muon --dataset_size 50 --batch_size 2 --num_epochs 1 --run_name "ci_test"

    - name: Deploy to HuggingFace
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        echo "Deploying to HuggingFace Space..."
        uv run python scripts/deploy_to_hf.py
