name: Validate Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-environment

    - name: Run OPT analysis
      run: uv run python playground/run_opt_locally.py

    - name: Run finetuning test
      run: uv run python playground/finetune_opt.py --optimizer muon --dataset_size 50 --batch_size 2 --num_epochs 1 --run_name "ci_test"
